In [10]:
from plotnine import *
import pandas as pd
import numpy as np

In [95]:
biology = pd.read_csv("Sugars.csv")
biology.head()

,Unnamed: 0,Base,C1'-C2',C1'-C2'-C3',C1'-C2'-O2',C1'-N1-C2/C1'-N9-C4,C1'-N1-C6/C1'-N9-C8,C1'-N1/C1'-N9,C1'-O4',C1'-O4'-C4',...,TAU_3,TAU_4,TCHI,T_max,Temperature,Theta,absChi,absChiDiff90,absGamma,absGammaDiff90
0,ASADED_0,purine,1.52055,101.179,NaN,129.430,124.819,1.44866,1.41992,108.669,...,18.68300,4.90456,73.2896,37.930611,198.0,154.246685,73.2896,16.7104,55.7218,34.2782
1,BAGVEK_1,purine,1.51247,103.689,NaN,127.539,125.450,1.45335,1.41698,107.887,...,-1.70027,22.86680,53.4063,35.484036,223.0,122.006573,53.4063,36.5937,173.3060,83.3060
2,CEZMEZ_6,purine,1.52724,105.870,NaN,125.101,128.863,1.44864,1.43244,107.494,...,-27.31290,37.50070,-117.9340,36.947289,295.0,76.535868,117.9340,27.9340,71.3444,18.6556
3,DEFPOT_8,purine,1.51487,103.234,NaN,127.407,126.155,1.45769,1.43526,109.179,...,12.97940,9.41205,-97.5776,35.512677,295.0,146.463599,97.5776,7.5776,170.6670,80.6670
4,DEHREN_9,purine,1.53450,102.981,NaN,126.250,126.758,1.46376,1.41303,110.578,...,-32.95290,21.86910,-116.5590,34.170488,295.0,20.793087,116.5590,26.5590,46.8008,43.1992

In [76]:
array = np.array(biology.columns)
angles = list(biology.columns)
angles = [x for x in list_of_bond_lengths if x.count("-") == 2 and x.count("/")==0]
angles

["C1'-C2'-C3'",
 "C1'-C2'-O2'",
 "C1'-O4'-C4'",
 "C2'-C1'-O4'",
 "C2'-C3'-C4'",
 "C2'-C3'-O3'",
 "C3'-C2'-O2'",
 "C3'-C4'-C5'",
 "C3'-C4'-O4'",
 "C4'-C3'-O3'",
 "C4'-C5'-O5'",
 "C5'-C4'-O4'"]

In [93]:
df = pd.DataFrame(columns=["AngleName","Sugar", "Value"])
for angle in angles:
    to_append = biology[["Sugar",angle]].set_index("Sugar").stack().reset_index().rename(columns={'level_1':'AngleName', 0:'Value'}).dropna(subset=["Value"])
    df = pd.concat([df,to_append])
#df = df.set_index("AngleName")
df.describe()
df.to_csv("Angle.csv", index=False)

In [94]:
df = pd.DataFrame(columns=["AngleName","Sugar", "Value"])
for angle in angles[:5]:
    to_append = biology[["Sugar",angle]].set_index("Sugar").stack().reset_index().rename(columns={'level_1':'AngleName', 0:'Value'}).dropna(subset=["Value"])
    df = pd.concat([df,to_append])
#df = df.set_index("AngleName")
df.describe()
df.to_csv("Angle5.csv", index=False)